---
- hosts: allnodes
  remote_user: "{{ osuser }}"
  #  become: yes
  #  become_user: root
  gather_facts: true
  vars_files:
    - neon_nodes.yml

  tasks:

    - name: create install dir
      file:
        path: "{{ installdir }}"
        state: "{{ item }}"
      with_items:
        - directory

    - name: Download Server
      get_url:
        url: "{{ downurl['neontargz'] }}"
        dest: "{{ installdir }}"
      tags: download,never

    - name: Install Neon components
      unarchive:
        src: "{{ downurl['neontargz'] }}"
        #        src: "{{ installdir }}/neondatabase-neon-PG14-1.0.0-Linux-x86_64.glibc2.35.tar.gz"
        dest: "{{ installdir }}"
        remote_src: yes
        extra_opts:
          - "--strip-components=1"
      tags: download

- hosts: pageserver
  remote_user: "{{ osuser }}"
  #  become: yes
  #  become_user: root
  gather_facts: true
  vars_files:
    - neon_nodes.yml

  tasks:

    - name: create data dir
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ installdir }}/neondata"
        - "{{ installdir }}/neondata/pg_install"

    - name: copy pg_install
      copy: src="{{ installdir }}/pg_install/v14" dest="{{ installdir }}/neondata/pg_install" remote_src=yes directory_mode=yes

# vim: set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
